version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./data:/data
    environment:
      - DATABASE_URL=/data/pokemon.db
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    command: ["/bin/sh", "-c", "sqlite3 /data/pokemon.db < /usr/src/app/src/database/migrations/001-create-pokemons.sql"]